import{useState,useEffect}from'react';
export const SS={Hadir:'bg-emerald-100 text-emerald-700 border-emerald-200',Menunggu:'bg-amber-100 text-amber-700 border-amber-200',Pulang:'bg-slate-100 text-slate-500 border-slate-200',Terlambat:'bg-orange-100 text-orange-700 border-orange-200',Izin:'bg-sky-100 text-sky-700 border-sky-200',Sakit:'bg-purple-100 text-purple-700 border-purple-200',Absen:'bg-red-100 text-red-600 border-red-200',Libur:'bg-indigo-100 text-indigo-700 border-indigo-200',Belum:'bg-slate-100 text-slate-400 border-slate-200'};
export function LogoMark({className='w-10 h-10 rounded-2xl'}){return <div className={`${className} bg-white border border-amber-100 shadow-sm flex items-center justify-center overflow-hidden flex-shrink-0`}><img src="/favicon.svg" alt="SIAGA" className="w-full h-full object-contain p-1"/></div>;}
export function Chip({status,manual}){return <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold border ${SS[status]||'bg-gray-100 text-gray-500'}`}>{!!manual&&<span className="opacity-60">✏</span>}{status||'Belum'}</span>;}
export function LiveClock({className=''}){const[t,setT]=useState(new Date());useEffect(()=>{const i=setInterval(()=>setT(new Date()),1000);return()=>clearInterval(i);},[]);return <span className={className}>{t.toLocaleTimeString('id-ID',{timeZone:'Asia/Jakarta'})}</span>;}
export function Toast({items}){return <div className="fixed bottom-4 inset-x-4 sm:inset-x-auto sm:bottom-5 sm:right-5 z-[100] flex flex-col gap-2 pointer-events-none">{items.map(t=><div key={t.id} className={`animate-slide-up px-4 py-3 rounded-2xl shadow-2xl text-sm font-semibold flex items-center gap-2 w-full sm:w-auto ${t.type==='ok'?'bg-emerald-600 text-white':t.type==='warn'?'bg-amber-500 text-white':'bg-red-600 text-white'}`}>{t.type==='ok'?'✅':t.type==='warn'?'⚠️':'🚨'} {t.msg}</div>)}</div>;}
export function Modal({title,onClose,children}){return <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" onClick={onClose}><div className="bg-white rounded-2xl w-full max-w-md max-h-[90vh] overflow-hidden shadow-2xl animate-bounce-in flex flex-col" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 flex-shrink-0"><h3 className="font-black text-lg text-slate-800 truncate pr-3">{title}</h3><button onClick={onClose} className="text-slate-400 hover:text-slate-600 text-xl flex-shrink-0">✕</button></div><div className="p-5 overflow-y-auto">{children}</div></div></div>;}
export function Spinner(){return <div className="flex items-center justify-center py-16"><div className="w-8 h-8 border-4 border-amber-200 border-t-amber-500 rounded-full animate-spin"/></div>;}
export function nowWIB(){const d=new Date();const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d);const get=t=>(p.find(x=>x.type===t)||{}).value||'';return{h:parseInt(get('hour'),10),m:parseInt(get('minute'),10)};}
export function todayWIB(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Jakarta'}).format(new Date());}
export function meniTunggu(j){if(!j)return null;const[h,m]=j.split(':').map(Number);const now=nowWIB();return Math.max(0,now.h*60+now.m-h*60-m);}
export function EmptyState({icon='📋',title,description,action}){return <div className="bg-slate-50 border border-slate-200 rounded-xl p-8 text-center space-y-3"><div className="text-4xl">{icon}</div><div className="font-black text-slate-700">{title}</div>{description&&<div className="text-sm text-slate-500">{description}</div>}{action&&<div>{action}</div>}</div>;}

